#!/bin/bash
set -e

# Aggiorna la cache delle icone
if [ -x /usr/bin/gtk-update-icon-cache ]; then
    gtk-update-icon-cache -f -t /usr/share/icons/hicolor 2>/dev/null || true
fi

# Aggiorna il database delle applicazioni
if [ -x /usr/bin/update-desktop-database ]; then
    update-desktop-database -q 2>/dev/null || true
fi

exit 0
